### ISSUE TITLE
Tantares new release, possible incompatibility

### ISSUE THREAD

**Issue by ImAHungryMan** [Raptor831/RFStockalike#13]
Just a heads up, Tantares 15.5 comes with its own set of Real Fuels configs and it's conflicting with the ones included in Stockalike. Not sure if you want to deprecate these or integrate the new ones.

**Comment by Raptor831** [comment]
Niemand303 (the author of the Tantares configs) and I should have worked that out previously to avoid exactly that. I'll have to double check the Tantares mod's file.

I want to keep these available, in case people want to use these instead of the Tantares ones.

**Comment by ImAHungryMan** [comment]
No problem thanks for the response. It's not a serious issue and it's easily rectified. I just wanted to let you know.

**Comment by Raptor831** [comment]
No, I'd rather someone keep me in the loop! I couldn't possibly keep up with all of these mods. So thank you!
