### ISSUE TITLE
KSPI - Possibly remove configs in favor of FreeThinkers

### ISSUE THREAD

**Issue by Raptor831** [Raptor831/RFStockalike#20]
This was brought up, so we can discuss it here.

I was not under the impression that FreeThinker's configs would interfere with the engines (since Northstar1989 has been very vocal if I goof anything up with KSPI). But I certainly could be wrong...

**Comment by ImAHungryMan** [comment]
I looked through both files and they seem to target the same parts. FreeThinker's are also more up-to-date while the ones included haven't been updated in a month. Which is understandable! Not trying to sound accusatory. Interstellar is weird.

Removing the RSStockalike KSPI files also seemed to solve some weird issues I was having.

I'll go ahead and ask FreeThinker and/or Northstar to confirm this on the forums.

**Comment by ImAHungryMan** [comment]
Also, it might be relevant to note that NathanKell has removed the KSPI config from the MFT side of things.

**Comment by Raptor831** [comment]
Ok. Yeah, no offense taken or anything. I don't even use KSPI at this point. Way to heavy for me, considering I only really wanted heat management. And it's the craziest mod to handle for me, because there's no "standard", everything is either a single case or it gets forced in within the plugin code. With the exception of the engines, I'd be ok just dropping the thing entirely.

**Comment by ImAHungryMan** [comment]
Sounds good. After talking with Northsar1989 and FreeThinker, it seems that they want RFStockalike to handle the chemical engines so we can keep those configs.

I'm still trying to get a firm answer on who should handle the resources and tanks. I think it makes the most sense that way. Kind of like how your Karbonite-Real Fuels configs are kept separate.

**Comment by Raptor831** [comment]
Tanks should be with FreeThinker/Northstar. This set of configs is for engines. NathanKell, et al, set it up to be separate, and I don't really see a good reason to change it. It keeps everything in its place without too much cross-contamination. Honestly, having the tank catch-all is a bit of a stretch, but I'll make an exception because it enables the engines to work with all tanks.

**Comment by ImAHungryMan** [comment]
On second thought, I may have been premature in asking for the configs to be removed. I suggest a "watch and shoot" approach for now. FreeThinker's stuff is still in development, after all.

**Comment by Raptor831** [comment]
Yeah, for now we can leave it. If FreeThinker/Northstar end up using a custom folder or a :FOR[...] piece in the MM configs, then I can even turn them off if their config is present, so there is no conflict even if both are installed.

**Comment by Raptor831** [comment]
Just as an update: if the conversation in the Community Resource Project thread is anything to go by, they won't "release" anything until 1.0 comes out (or at least 1.0 of CRP) comes out. There will be breaking changes in CRP for pretty much every mod that uses it (now including RF). RF won't be changed much, just a few density numbers really and possibly a resource or two renamed. But, until then I'll probably leave the KSPI stuff just for the sake of completeness.

**Comment by ImAHungryMan** [comment]
Yep no problem. I'm the only one who seems bothered by it and I can simply
remove them from my install anyway. Pretty cool initiative on the modders'
part by the way.

**Comment by Raptor831** [comment]
Gonna close this one out until we hear from FreeThinker or any of the KSPI people.
