### ISSUE TITLE
Change Starshine config to the new methalox thrust scaling

### ISSUE THREAD

**Issue by Raptor831** [Raptor831/RFStockalike#25]
Same as SpaceY, need to get the methalox numbers in line, and really get the engines into the webapp.

**Comment by ImAHungryMan** [comment]
Are you asking for a volunteer? Because by happenstance I am currently tweaking the StarShine engines along with some other ones.

**Comment by Raptor831** [comment]
No, I wasn't actually! I just wanted a reminder for myself. If you're doing them already though I don't mind.

**Comment by ImAHungryMan** [comment]
Cool. Since it's based on a real engine, do you prefer basing the stats off of real life (Wikipedia :P) or do you want them kept more or less as the mod author intended them?

**Comment by Raptor831** [comment]
For Stockalike, I'd lean towards how it's worked out in the original config. I've mentioned this other places before (so you might have seen it), but I tend to keep stock/original thrust intact, and then adjust the mass and such around that. Isp, TWR, and the like should follow reality, but I don't usually make a point of keeping them exact. That said, if you do match to some real data, I wouldn't mind.

**Comment by ImAHungryMan** [comment]
Okay heads up. Am submitting Starshine engines now.

How do you identify which mod an engine is from anyway? Assuming an anonymous webapp submission.

**Comment by Raptor831** [comment]
Well, quick question: did you use the prompt? It's not coming through in the notifications I'm receiving, and if you filled it out it means I messed up the code.

**Comment by ImAHungryMan** [comment]
Yep sent them all last night under "Starshine Industries". I hit " Submit
Engine" and a little text box popped up saying it was submitted.

**Comment by Raptor831** [comment]
Ok, thanks. Will have to fix that on my end, but I know that whatever was sent at least was Starshine. I'll get those in this evening, hopefully.

**Comment by ImAHungryMan** [comment]
Thrust scaling applied.
