### ISSUE TITLE
Engine Ignitor support

### ISSUE THREAD

**Issue by ImAHungryMan** [Raptor831/RFStockalike#27]
Hello,

I noticed that a lot of the engines don't have the correct amount of available ignitions according to their type. For example, a lot of Orbital or Upper engines have only one available ignition.

Is this something you can perhaps write a script for? Check for engine type and assign the correct amount of ignitions?

Not exactly the highest priority since no one seems to be complaining yet and Engine Ignitor isn't updated for 0.90.

**Comment by Raptor831** [comment]
They all should be set up within the webapp. The app does some hoop-jumping to arrive at a given number, though. I'll check it out when I get some time. Orbitals should default to like 24 ignitions minimum...

**Comment by ImAHungryMan** [comment]
Right. The app seems to work fine in that regard. But a few engines appear
to have been missed here and there.

**Comment by Raptor831** [comment]
It could also be that I've set some of the engines to respect hypergolic fuel rules (i.e. no restarts unless the fuels are hypergolic). There are a number of mixtures in the app that may not be marked properly in that regard.

**Comment by ImAHungryMan** [comment]
If it turns out that's the case then I apologize. I was going by the
assumption that available ignitions was determined by engine type.

**Comment by Raptor831** [comment]
If that's the case, it's still a bug. ;-) It sounds about right too, the engine types. If there are any that specifically should have more ignitions, let me know. I'll double-check the app though, considering I know there's a few mixtures that need to be marked appropriately.

**Comment by ImAHungryMan** [comment]
Okay the "problem" appears to be concentrated around the historical engines. For example, the RD-183 from KOSMOS is an upper-stage engine that uses Methalox. The fact that it's an upper-stage engine should mean that it has at least six ignitions, but since it uses Methalox it only gets one.

So it comes down to gameplay vs. authenticity really.

And a quick look around seems to confirm that your app is working okay. Orbital engines do get 24 ignitions so long as they use hypergolic propellants. And so on and so forth.

**Comment by Raptor831** [comment]
You can force override the hypergolic settings as well, which is done just for this case. The J-2 engine on the S-IVB stage was obviously ignited twice on every mission, but it used hydrolox. I believe the J-2 clones in Stockalike should be rated at 4 ignitions. Just set the EI Mode in the app to "Ignore Hypergolic Rules" and it'll force the ignitions to whatever you set.

I did a quick run around the app and double-checked the files, and it seems the majority are from engines I do not have within the app. If you find them you can submit pull requests to correct the ignitions. In the meantime, I'll try and get them into the app so they're a bit more editable down the road.

**Comment by ImAHungryMan** [comment]
Sounds good. I'll take care of the repo side then? So can we agree on L,
L+, U, U+, O having 1, 2, 6, 12, 24 ignitions respectively? The exceptions
being historical engines which will be case-by-case assuming there is
relevant data available.

**Comment by ImAHungryMan** [comment]
Also, VTOLs should probably have infinite ignitions for gameplay purposes,
correct? And how should Aerospikes be handled?

**Comment by Raptor831** [comment]
The defaults in the app are 1,2,4,12,24 ignitions for L,L+,U,U+,O respectively. Though, exceptions can and already have been made (Merlin 1D engines for example, 4 ignitions for an L+ engine). It's really more about what the engine was designed to do, with the "defaults" being reasonable fallbacks.

As for VTOLs, those should be rated for either unlimited (in-config 0) or 24+ ignitions. Aerospikes default to unlimited. Just use good judgment. As I said, it's more about getting the intended use of the engine correct.

Anything based on historical or current engines you can certainly adjust beyond what the "defaults" are. Or, even if an engine isn't historical/current but intends to fill the same role, use the data if it works well. Then, err on the side of too many ignitions, just for the sake of gameplay.

**Comment by ImAHungryMan** [comment]
Will do. Thanks!
