### ISSUE TITLE
Throttle limits not working

### ISSUE THREAD

**Issue by lurkoholic** [Raptor831/RFStockalike#41]
Engines with throttle limits are fully throttleable. One example of this is the LV-T15 from Ven's Stock Revamp (added in my most recent pull request), which has a Min Throttle of 100% at low tech levels.

**Comment by Raptor831** [comment]
The config is correct in the repo right now. Or, at least as correct as I know how to do it. Which is also how it was when you did your PR.

Haven't tested directly, but it looks like it's *supposed* to be working. :-/ Will run some tests on my end.

**Comment by lurkoholic** [comment]
Fixed by updated Real Fuels v10.6.1.
