### ISSUE TITLE
Upper Stages

### ISSUE THREAD

**Issue by blowfishpro** [Raptor831/RFStockalike#42]
There are a couple of engines which I will argue should be upper stages, but are currently marked as lowers.  I can make the config changes myself and submit a pull request, but I wanted to run them by you first.

#### Squad

* __KR-2L "Rhino"__: tech description and post-1.0 Isp (255-340s) definitely peg it as an upper stage

#### KW

* __Titan V__: The tech description says it *can* be used as a lower stage so I guess this could be argued either way.  The obvious RL equivalent though is the Saturn V second stage which is definitely an upper.  Slight complication in that comparison though - SII uses J-2 engines which are gas generator cycle engines and thus will have somewhat lower Isp than the RF stockalike calcs will predict - is that at all worth accounting for?

#### CryoEngines

* __Ct10 "Chelyabinsk"__: Tech description and extendable nozzle peg it as U+

* __CT2X "Tunguska"__: Low SL Isp pegs it as an upper, not to mention it completes the pattern of one lower and one upper per size in this pack.  Not sure about U vs U+ though.

* __Ct5 "Yucatan"__: Tech description and Isp make this solidly an upper.

**Comment by Raptor831** [comment]
## Squad
### KR-2L
I never seem to be able to use as an upper. It's too much thrust for that, it seems. L+ is kind of a compromise. It's Isp is enough that it works as a 2nd stage but could launch as well. Kerolox is 285/347 Isp. Hydrolox is way better, but with the reduced thrust. So really, could be argued that the Hydrolox is the upper variant and the Kerolox is the lower variant. 

And hey, it's got an "L+" in the name. ;-)

## KW
### Titan V

I'll switch that to Upper. It is a SII clone, pretty much, and they are J2s. So makes sense. Scaled the Isp to 99% of what it "should" be.

## CryoEngines
### CT10

This is an U+.

### CT2X

Was supposed to be a U, wasn't properly set.

### CT5

This is a U.


Note, I checked these against the current repo. The release version may not be totally up to date.

**Comment by blowfishpro** [comment]
Makes sense, and I was probably going off of release rather than current.  I've definitely managed to use the KL-2L+ as an upper for very heavy payloads, but I can see other use cases as well.

**Comment by blowfishpro** [comment]
I think this is done now
