### ISSUE TITLE
Atomic Age engines missing

### ISSUE THREAD

**Issue by TomatoCo** [Raptor831/RFStockalike#44]
Atomic Age is missing it's atmos-breathing engine and the small RTG-derivative engine. There are also radiators that were recently added to the pack but I don't think that the fuel configs concern themselves about those.

**Comment by Raptor831** [comment]
The atmo engines I don't mess with, largely because the math to deal with that is wildly different. Not to mention jets/air-breathers are better suited to a different engine module. So, I leave Advanced Jet Engine  to take care of that.

I added the Candle one from the pack, though.
