### ISSUE TITLE
Add Cormorant Aeronology

### ISSUE THREAD

**Issue by Raptor831** [Raptor831/RFStockalike#60]

**Comment by gparent** [comment]
I would appreciate this as I've been unable to make my own configs successfully.

**Comment by Raptor831** [comment]
Added this one today. If you find issues, let me know.

**Comment by gparent** [comment]
I will test it out! thank you

**Comment by gparent** [comment]
Hello.

The config appears fine for the front nose and the orbital pods. However the shuttle lifting body itself includes the back tank and that one is still using the old "Next tank setup" buttons.

Thank you for your work

**Comment by Raptor831** [comment]
The tanks are outside the scope of these configs. It would be better to submit a PR to RealFuels directly to add the tanks there. I do have a catch all, but it doesn't fix everything properly.

That said, I'd do something like this:
```@PART[ShuttleBottomLong]
{
  MODULE
  {
    name = ModuleFuelTanks
    volume = 5000
    basemass = -1 // don't want to mess with the mass of the rest of the piece
    type = ServiceModule // can put anything in here, from MMH/NTO to LS resources
  }
  !MODULE[FSfuelSwitch]{} // removes the fuel switcher
}```

It should at least take care of the long piece.

**Comment by gparent** [comment]
Oh sorry, I didn't know your mod focused on the engines :) I must not use enough other parts than the ones you've taken time to modify to notice.

Thank you so much for taking some more for writing down a config, I will try it.
