### ISSUE TITLE
Inconsistent role for SXT BlackAdder engines

### ISSUE THREAD

**Issue by bfrobin446** [Raptor831/RFStockalike#68]
The SXT "BlackAdder" engines are set up with the 0.625m version as type L and the 1.25m version as type O. The historical versions, the Bristol Siddeley [Gamma 2](http://www.astronautix.com/engines/gamma2.htm) and [Gamma 8](http://www.astronautix.com/engines/gamma8.htm), are both listed on the linked site as having the same Isp curve: 251 sea level and 265 vacuum.

Changing the 1.25m BlackAdder 8 to type L would be a closer match to the historical engine, and I think it would make it a more useful engine.

**Comment by Raptor831** [comment]
Didn't realize they were that off. Thanks for pointing that out.

**Comment by bfrobin446** [comment]
Update looks good to me.
