### ISSUE TITLE
can not I edit resources bag

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [Raptor831/RFStockalike#81]
![screenshot0](https://cloud.githubusercontent.com/assets/4707623/22699965/990829f0-ed1e-11e6-971b-d6464770d3d4.png)

I have not been able add htp for rcs 
![screenshot1](https://cloud.githubusercontent.com/assets/4707623/22700020/cec9bf04-ed1e-11e6-89fe-f3676bca9b64.png)

**Comment by blowfishpro** [comment]
You probably don't have Community Resource Pack installed.  It is required for RF.

**Comment by REVIEWGAMINGMAN** [comment]
did updete for Community Resource Pack

**Comment by Raptor831** [comment]
This probably doesn't have anything to do with the engine configs directly. I don't mess with a lot of fuel tank configs, and what I do is basically a catch-all to make sure tanks at least have a MFT on it somewhere with reasonable sizing.

As @blowfishpro mentioned, it looks like you're plain missing fuels. Also, you wouldn't happen to have both Real Fuels and Modular Fuel Tanks installed, would you?

**Comment by REVIEWGAMINGMAN** [comment]
yes

**Comment by blowfishpro** [comment]
If you have both RF and MFT installed, then that's probably your issue.  They are incompatible.  RF provides all the tank switching functionality.
