### ISSUE TITLE
Fix NFSpacecraft configs

### ISSUE THREAD

**Issue by TotallyNotHuman** [Raptor831/RFStockalike#85]
Hey @Raptor831 ,

Not sure if you're aware of this issue or not, but the engines implemented by NFSpacecraft [LV-T95, LV-T95-8, and LV-T18] were deprecated back in v0.6.1.  The new engines, therefore, do not have RL fuel mixtures; they just run on Monopropellant now.

I'm not very knowledgeable about real engine configs; however, I will try my best (and probably submit a PR later). If I make a fool of myself in making real configs for those engines, please point that out to me.

Thanks in advance.

**Comment by Raptor831** [comment]
Thanks for the notice! Do submit a PR and I'll have a look. If you use the generator (http://bit.ly/rfstockalike) you should not have too many issues.
