### ISSUE TITLE
Downloads for v3.2.5.4 and v3.2.6 are empty

### ISSUE THREAD

**Issue by HebaruSan** [Raptor831/RFStockalike#98]
Both of these versions are 176 **bytes**, containing only a directory called `RFStockalike` and no files.

- https://github.com/Raptor831/RFStockalike/releases/download/v3.2.6/RFStockalike--v3.2.6-33.zip
- https://github.com/Raptor831/RFStockalike/releases/download/v3.2.5.4/RFStockalikeRFStockalike--v3.2.5.4-32.zip

**Comment by Raptor831** [comment]
@HebaruSan should be building a proper .zip now.
